import { FlashCardTile } from 'src/app/interfaces/flashCards/flash-card-tile'

export function allKatakanaTiles(): FlashCardTile[] {
	return [...compoundKatakana(), ...allSingleCharacterKatakana()]
}

export function allSingleCharacterKatakana(): FlashCardTile[] {
	return [...singleCharacterKatakanaClean(), ...singleCharacterKatakanaTenTen(), ...singleCharacterKatakanaMaru()]
}
export function singleCharacterKatakanaClean(): FlashCardTile[] {
	return [
		{ front: { text: 'ア' }, back: { text: 'a' } },
		{ front: { text: 'イ' }, back: { text: 'i' } },
		{ front: { text: 'ウ' }, back: { text: 'u' } },
		{ front: { text: 'エ' }, back: { text: 'e' } },
		{ front: { text: 'オ' }, back: { text: 'o' } },
		{ front: { text: 'カ' }, back: { text: 'ka' } },
		{ front: { text: 'キ' }, back: { text: 'ki' } },
		{ front: { text: 'ク' }, back: { text: 'ku' } },
		{ front: { text: 'ケ' }, back: { text: 'ke' } },
		{ front: { text: 'コ' }, back: { text: 'ko' } },
		{ front: { text: 'サ' }, back: { text: 'sa' } },
		{ front: { text: 'シ' }, back: { text: 'shi' } },
		{ front: { text: 'ス' }, back: { text: 'su' } },
		{ front: { text: 'セ' }, back: { text: 'se' } },
		{ front: { text: 'ソ' }, back: { text: 'so' } },
		{ front: { text: 'タ' }, back: { text: 'ta' } },
		{ front: { text: 'チ' }, back: { text: 'chi' } },
		{ front: { text: 'ツ' }, back: { text: 'tsu' } },
		{ front: { text: 'テ' }, back: { text: 'te' } },
		{ front: { text: 'ト' }, back: { text: 'to' } },
		{ front: { text: 'ナ' }, back: { text: 'na' } },
		{ front: { text: 'ニ' }, back: { text: 'ni' } },
		{ front: { text: 'ヌ' }, back: { text: 'nu' } },
		{ front: { text: 'ネ' }, back: { text: 'ne' } },
		{ front: { text: 'ノ' }, back: { text: 'no' } },
		{ front: { text: 'ハ' }, back: { text: 'ha' } },
		{ front: { text: 'ヒ' }, back: { text: 'hi' } },
		{ front: { text: 'フ' }, back: { text: 'fu' } },
		{ front: { text: 'ヘ' }, back: { text: 'he' } },
		{ front: { text: 'ホ' }, back: { text: 'ho' } },
		{ front: { text: 'マ' }, back: { text: 'ma' } },
		{ front: { text: 'ミ' }, back: { text: 'mi' } },
		{ front: { text: 'ム' }, back: { text: 'mu' } },
		{ front: { text: 'メ' }, back: { text: 'me' } },
		{ front: { text: 'モ' }, back: { text: 'mo' } },
		{ front: { text: 'ヤ' }, back: { text: 'ya' } },
		{ front: { text: 'ユ' }, back: { text: 'yu' } },
		{ front: { text: 'ヨ' }, back: { text: 'yo' } },
		{ front: { text: 'ラ' }, back: { text: 'ra' } },
		{ front: { text: 'リ' }, back: { text: 'ri' } },
		{ front: { text: 'ル' }, back: { text: 'ru' } },
		{ front: { text: 'レ' }, back: { text: 're' } },
		{ front: { text: 'ロ' }, back: { text: 'ro' } },
		{ front: { text: 'ワ' }, back: { text: 'wa' } },
		{ front: { text: 'ン' }, back: { text: 'n' } },
	]
}
export function singleCharacterKatakanaTenTen(): FlashCardTile[] {
	return [
		{ front: { text: 'ガ' }, back: { text: 'ga' } },
		{ front: { text: 'ギ' }, back: { text: 'gi' } },
		{ front: { text: 'グ' }, back: { text: 'gu' } },
		{ front: { text: 'ゲ' }, back: { text: 'ge' } },
		{ front: { text: 'ゴ' }, back: { text: 'go' } },
		{ front: { text: 'ザ' }, back: { text: 'za' } },
		{ front: { text: 'ジ' }, back: { text: 'ji' } },
		{ front: { text: 'ズ' }, back: { text: 'zu' } },
		{ front: { text: 'ゼ' }, back: { text: 'ze' } },
		{ front: { text: 'ゾ' }, back: { text: 'zo' } },
		{ front: { text: 'バ' }, back: { text: 'ba' } },
		{ front: { text: 'ビ' }, back: { text: 'bi' } },
		{ front: { text: 'ブ' }, back: { text: 'bu' } },
		{ front: { text: 'ベ' }, back: { text: 'be' } },
		{ front: { text: 'ボ' }, back: { text: 'bo' } },
		{ front: { text: 'ダ' }, back: { text: 'da' } },
		{ front: { text: 'ヂ' }, back: { text: 'ji' } },
		{ front: { text: 'ヅ' }, back: { text: 'zu' } },
		{ front: { text: 'デ' }, back: { text: 'de' } },
		{ front: { text: 'ド' }, back: { text: 'do' } },
	]
}
export function singleCharacterKatakanaMaru(): FlashCardTile[] {
	return [
		{ front: { text: 'パ' }, back: { text: 'pa' } },
		{ front: { text: 'ピ' }, back: { text: 'pi' } },
		{ front: { text: 'プ' }, back: { text: 'pu' } },
		{ front: { text: 'ペ' }, back: { text: 'pe' } },
		{ front: { text: 'ポ' }, back: { text: 'po' } },
	]
}
export function compoundKatakana(): FlashCardTile[] {
	return [
		{ front: { text: 'キャ' }, back: { text: 'kya' } },
		{ front: { text: 'キュ' }, back: { text: 'kyu' } },
		{ front: { text: 'キョ' }, back: { text: 'kyo' } },
		{ front: { text: 'シャ' }, back: { text: 'sha' } },
		{ front: { text: 'シュ' }, back: { text: 'shu' } },
		{ front: { text: 'ショ' }, back: { text: 'sho' } },
		{ front: { text: 'チャ' }, back: { text: 'cha' } },
		{ front: { text: 'チュ' }, back: { text: 'chu' } },
		{ front: { text: 'チョ' }, back: { text: 'cho' } },
		{ front: { text: 'ニャ' }, back: { text: 'nya' } },
		{ front: { text: 'ニュ' }, back: { text: 'nyu' } },
		{ front: { text: 'ニョ' }, back: { text: 'nyo' } },
		{ front: { text: 'ヒャ' }, back: { text: 'hya' } },
		{ front: { text: 'ヒュ' }, back: { text: 'hyu' } },
		{ front: { text: 'ヒョ' }, back: { text: 'hyo' } },
		{ front: { text: 'ミャ' }, back: { text: 'mya' } },
		{ front: { text: 'ミュ' }, back: { text: 'myu' } },
		{ front: { text: 'ミョ' }, back: { text: 'myo' } },
		{ front: { text: 'リャ' }, back: { text: 'rya' } },
		{ front: { text: 'リュ' }, back: { text: 'ryu' } },
		{ front: { text: 'リョ' }, back: { text: 'ryo' } },
		{ front: { text: 'ギャ' }, back: { text: 'gya' } },
		{ front: { text: 'ギュ' }, back: { text: 'guy' } },
		{ front: { text: 'ギョ' }, back: { text: 'gyo' } },
		{ front: { text: 'ジャ' }, back: { text: 'ja' } },
		{ front: { text: 'ジュ' }, back: { text: 'ju' } },
		{ front: { text: 'ジョ' }, back: { text: 'jo' } },
		{ front: { text: 'ビャ' }, back: { text: 'bya' } },
		{ front: { text: 'ビュ' }, back: { text: 'byu' } },
		{ front: { text: 'ビョ' }, back: { text: 'byo' } },
		{ front: { text: 'ピャ' }, back: { text: 'pya' } },
		{ front: { text: 'ピュ' }, back: { text: 'pyu' } },
		{ front: { text: 'ピョ' }, back: { text: 'pyo' } },
		{ front: { text: 'ファ' }, back: { text: 'fa' } },
		{ front: { text: 'フィ' }, back: { text: 'fi' } },
		{ front: { text: 'フェ' }, back: { text: 'fe' } },
		{ front: { text: 'フォ' }, back: { text: 'fo' } },
		{ front: { text: 'ツァ' }, back: { text: 'tsa' } },
		{ front: { text: 'ティ' }, back: { text: 'ti' } },
		{ front: { text: 'トゥ' }, back: { text: 'tu' } },
		{ front: { text: 'ウェ' }, back: { text: 'we' } },
		{ front: { text: 'ウォ' }, back: { text: 'wo' } },
	]
}

export function allHiraganaTiles(): FlashCardTile[] {
	return [...compoundHiragana(), ...allSingleCharacterHiragana()]
}

export function allSingleCharacterHiragana(): FlashCardTile[] {
	return [...singleCharacterHiraganaClean(), ...singleCharacterHiraganaTenTen(), ...singleCharacterHiraganaMaru()]
}
export function singleCharacterHiraganaClean(): FlashCardTile[] {
	return [
		{ front: { text: 'あ' }, back: { text: 'a' } },
		{ front: { text: 'い' }, back: { text: 'i' } },
		{ front: { text: 'う' }, back: { text: 'u' } },
		{ front: { text: 'え' }, back: { text: 'e' } },
		{ front: { text: 'お' }, back: { text: 'o' } },
		{ front: { text: 'か' }, back: { text: 'ka' } },
		{ front: { text: 'き' }, back: { text: 'ki' } },
		{ front: { text: 'く' }, back: { text: 'ku' } },
		{ front: { text: 'け' }, back: { text: 'ke' } },
		{ front: { text: 'こ' }, back: { text: 'ko' } },
		{ front: { text: 'さ' }, back: { text: 'sa' } },
		{ front: { text: 'し' }, back: { text: 'shi' } },
		{ front: { text: 'す' }, back: { text: 'su' } },
		{ front: { text: 'せ' }, back: { text: 'se' } },
		{ front: { text: 'そ' }, back: { text: 'so' } },
		{ front: { text: 'た' }, back: { text: 'ta' } },
		{ front: { text: 'ち' }, back: { text: 'chi' } },
		{ front: { text: 'つ' }, back: { text: 'tsu' } },
		{ front: { text: 'て' }, back: { text: 'te' } },
		{ front: { text: 'と' }, back: { text: 'to' } },
		{ front: { text: 'な' }, back: { text: 'na' } },
		{ front: { text: 'に' }, back: { text: 'ni' } },
		{ front: { text: 'ぬ' }, back: { text: 'nu' } },
		{ front: { text: 'ね' }, back: { text: 'ne' } },
		{ front: { text: 'の' }, back: { text: 'no' } },
		{ front: { text: 'は' }, back: { text: 'ha' } },
		{ front: { text: 'ひ' }, back: { text: 'hi' } },
		{ front: { text: 'ふ' }, back: { text: 'fu' } },
		{ front: { text: 'へ' }, back: { text: 'he' } },
		{ front: { text: 'ほ' }, back: { text: 'ho' } },
		{ front: { text: 'ま' }, back: { text: 'ma' } },
		{ front: { text: 'み' }, back: { text: 'mi' } },
		{ front: { text: 'む' }, back: { text: 'mu' } },
		{ front: { text: 'め' }, back: { text: 'me' } },
		{ front: { text: 'も' }, back: { text: 'mo' } },
		{ front: { text: 'や' }, back: { text: 'ya' } },
		{ front: { text: 'ゆ' }, back: { text: 'yu' } },
		{ front: { text: 'よ' }, back: { text: 'yo' } },
		{ front: { text: 'ら' }, back: { text: 'ra' } },
		{ front: { text: 'り' }, back: { text: 'ri' } },
		{ front: { text: 'る' }, back: { text: 'ru' } },
		{ front: { text: 'れ' }, back: { text: 're' } },
		{ front: { text: 'ろ' }, back: { text: 'ro' } },
		{ front: { text: 'わ' }, back: { text: 'wa' } },
		{ front: { text: 'ん' }, back: { text: 'n' } },
	]
}
export function singleCharacterHiraganaTenTen(): FlashCardTile[] {
	return [
		{ front: { text: 'が' }, back: { text: 'ga' } },
		{ front: { text: 'ぎ' }, back: { text: 'gi' } },
		{ front: { text: 'ぐ' }, back: { text: 'gu' } },
		{ front: { text: 'げ' }, back: { text: 'ge' } },
		{ front: { text: 'ご' }, back: { text: 'go' } },
		{ front: { text: 'ざ' }, back: { text: 'za' } },
		{ front: { text: 'じ' }, back: { text: 'ji' } },
		{ front: { text: 'ず' }, back: { text: 'zu' } },
		{ front: { text: 'ぜ' }, back: { text: 'ze' } },
		{ front: { text: 'ぞ' }, back: { text: 'zo' } },
		{ front: { text: 'ば' }, back: { text: 'ba' } },
		{ front: { text: 'び' }, back: { text: 'bi' } },
		{ front: { text: 'ぶ' }, back: { text: 'bu' } },
		{ front: { text: 'べ' }, back: { text: 'be' } },
		{ front: { text: 'ぼ' }, back: { text: 'bo' } },
		{ front: { text: 'だ' }, back: { text: 'da' } },
		{ front: { text: 'ぢ' }, back: { text: 'ji' } },
		{ front: { text: 'づ' }, back: { text: 'zu' } },
		{ front: { text: 'で' }, back: { text: 'de' } },
		{ front: { text: 'ど' }, back: { text: 'do' } },
	]
}
export function singleCharacterHiraganaMaru(): FlashCardTile[] {
	return [
		{ front: { text: 'ぱ' }, back: { text: 'pa' } },
		{ front: { text: 'ぴ' }, back: { text: 'pi' } },
		{ front: { text: 'ぷ' }, back: { text: 'pu' } },
		{ front: { text: 'ぺ' }, back: { text: 'pe' } },
		{ front: { text: 'ぽ' }, back: { text: 'po' } },
	]
}
export function compoundHiragana(): FlashCardTile[] {
	return [
		{ front: { text: 'きゃ' }, back: { text: 'kya' } },
		{ front: { text: 'きゅ' }, back: { text: 'kyu' } },
		{ front: { text: 'きょ' }, back: { text: 'kyo' } },
		{ front: { text: 'しゃ' }, back: { text: 'sha' } },
		{ front: { text: 'しゅ' }, back: { text: 'shu' } },
		{ front: { text: 'しょ' }, back: { text: 'sho' } },
		{ front: { text: 'ちゃ' }, back: { text: 'cha' } },
		{ front: { text: 'ちゅ' }, back: { text: 'chu' } },
		{ front: { text: 'ちょ' }, back: { text: 'cho' } },
		{ front: { text: 'にゃ' }, back: { text: 'nya' } },
		{ front: { text: 'にゅ' }, back: { text: 'nyu' } },
		{ front: { text: 'にょ' }, back: { text: 'nyo' } },
		{ front: { text: 'ひゃ' }, back: { text: 'hya' } },
		{ front: { text: 'ひゅ' }, back: { text: 'hyu' } },
		{ front: { text: 'ひょ' }, back: { text: 'hyo' } },
		{ front: { text: 'みゃ' }, back: { text: 'mya' } },
		{ front: { text: 'みゅ' }, back: { text: 'myu' } },
		{ front: { text: 'みょ' }, back: { text: 'myo' } },
		{ front: { text: 'りゃ' }, back: { text: 'rya' } },
		{ front: { text: 'りゅ' }, back: { text: 'ryu' } },
		{ front: { text: 'りょ' }, back: { text: 'ryo' } },
		{ front: { text: 'ぎゃ' }, back: { text: 'gya' } },
		{ front: { text: 'ぎゅ' }, back: { text: 'guy' } },
		{ front: { text: 'ぎょ' }, back: { text: 'gyo' } },
		{ front: { text: 'じゃ' }, back: { text: 'ja' } },
		{ front: { text: 'じゅ' }, back: { text: 'ju' } },
		{ front: { text: 'じょ' }, back: { text: 'jo' } },
		{ front: { text: 'びゃ' }, back: { text: 'bya' } },
		{ front: { text: 'びゅ' }, back: { text: 'byu' } },
		{ front: { text: 'びょ' }, back: { text: 'byo' } },
		{ front: { text: 'ぴゃ' }, back: { text: 'pya' } },
		{ front: { text: 'ぴゅ' }, back: { text: 'pyu' } },
		{ front: { text: 'ぴょ' }, back: { text: 'pyo' } },
		{ front: { text: 'ふぁ' }, back: { text: 'fa' } },
		{ front: { text: 'ふぃ' }, back: { text: 'fi' } },
		{ front: { text: 'ふぇ' }, back: { text: 'fe' } },
		{ front: { text: 'ふぉ' }, back: { text: 'fo' } },
		{ front: { text: 'つぁ' }, back: { text: 'tsa' } },
		{ front: { text: 'てぃ' }, back: { text: 'ti' } },
		{ front: { text: 'とぅ' }, back: { text: 'tu' } },
		{ front: { text: 'うぇ' }, back: { text: 'we' } },
		{ front: { text: 'うぉ' }, back: { text: 'wo' } },
	]
}
